name: GUIWorkflow
on: 
  pull_request:
    branches:
      - main

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    steps:
      - name: Set Secret
        shell: bash
    env: 
        TokenVar: ${{secrets.CLIENT_TOKEN}}
